export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",

  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",

  EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",

  NETWORK_ERROR: "AUTH_NETWORK_ERROR",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
